[build]
  publish = "dist/public"
  command = "npm ci && node scripts/netlify-build-simple.cjs"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"
  # Explicitly disable Python to avoid conflicts
  PYTHON_VERSION = ""
  DISABLE_PYTHON = "true"
  # Use Netlify-specific Vite config
  VITE_CONFIG_FILE = "vite.config.netlify.ts"
  
  # متغيرات Supabase - يجب إعدادها في Netlify Dashboard
  # Supabase variables - must be set in Netlify Dashboard
  VITE_SUPABASE_URL = "https://yieyqusnciiithjtlgod.supabase.co"
  # VITE_SUPABASE_ANON_KEY = "your-anon-key"
  # SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"  
  # SUPABASE_JWT_SECRET = "your-jwt-secret"
  VITE_API_BASE_URL = "/.netlify/functions"
  VITE_APP_ENV = "production"

[context.production.environment]
  NODE_ENV = "production"
  VITE_APP_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"
  VITE_APP_ENV = "preview"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "cors", "helmet"]

# توجيهات API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# توجيهات التطبيق الرئيسي - إعادة توجيه جميع المسارات إلى index.html لـ SPA
[[redirects]]
  from = "/app"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html" 
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/transactions"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/transactions/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/customers"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/customers/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/projects/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/users"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/users/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reports"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reports/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/settings/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/documents"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/documents/*"
  to = "/index.html"
  status = 200

# صفحة الترحيب fallback - لدعم SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# إعدادات الأمان المتقدمة
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# تحسين cache للملفات الثابتة
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# إعدادات PWA
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"
