[build]
  publish = "dist/public"
  command = "npm ci && node scripts/netlify-build-simple.cjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"
  PYTHON_VERSION = ""
  DISABLE_PYTHON = "true"
  VITE_CONFIG_FILE = "vite.config.netlify.ts"

  # ✅ هذه القيم تُقرأ الآن من لوحة Netlify فقط:
  # VITE_SUPABASE_URL ← موجودة في Dashboard
  # VITE_SUPABASE_ANON_KEY ← موجودة في Dashboard

[context.production.environment]
  NODE_ENV = "production"
  VITE_APP_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"
  VITE_APP_ENV = "preview"

# توجيهات SPA - جميع المسارات تذهب إلى التطبيق
[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/transactions"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/transactions/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/customers"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/customers/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/reports"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/reports/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/settings/*"
  to = "/app.html"
  status = 200

# الصفحة الرئيسية للترحيب
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# رؤوس الأمان والأداء
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"
